window.JOB_DATA = [
  {
    "id": "anu-research-jobs-analytics-and-data-developer",
    "title": "Analytics & Data Developer",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Analytics & Data Developer.",
    "url": "https://jobs.anu.edu.au/jobs/analytics-data-developer-canberra-act-act-australia"
  },
  {
    "id": "anu-research-jobs-director-australian-data-archive",
    "title": "Director, Australian Data Archive",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Director, Australian Data Archive.",
    "url": "https://jobs.anu.edu.au/jobs/director-australian-data-archive-canberra-act-act-australia"
  },
  {
    "id": "anu-research-jobs-senior-research-advisor",
    "title": "Senior Research Advisor",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Senior Research Advisor.",
    "url": "https://jobs.anu.edu.au/jobs/senior-research-advisor-canberra-act-act-australia-52546af7-a9ee-48e8-92bb-e5bbe15580cf"
  },
  {
    "id": "anu-research-jobs-manager-library-innovation-and-ai",
    "title": "Manager, Library Innovation & AI",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Manager, Library Innovation & AI.",
    "url": "https://jobs.anu.edu.au/jobs/manager-library-innovation-ai-canberra-act-act-australia"
  },
  {
    "id": "anu-research-jobs-postdoctoral-research-fellow",
    "title": "Postdoctoral/Research Fellow",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Postdoctoral/Research Fellow.",
    "url": "https://jobs.anu.edu.au/jobs/postdoctoral-research-fellow-canberra-act-act-australia-acd83393-b812-4ae1-926d-1976b65b2a5f"
  },
  {
    "id": "anu-research-jobs-maintenance-support-officer",
    "title": "Maintenance Support Officer",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Maintenance Support Officer.",
    "url": "https://jobs.anu.edu.au/jobs/maintenance-support-officer-canberra-act-act-australia"
  },
  {
    "id": "linkedin-au-cyber-jobs-skip-to-main-content",
    "title": "Skip to main content",
    "organization": "linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from linkedin.com: Skip to main content.",
    "url": "https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia#main-content"
  },
  {
    "id": "linkedin-au-cyber-jobs-join-now",
    "title": "Join now",
    "organization": "linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from linkedin.com: Join now.",
    "url": "https://www.linkedin.com/signup/cold-join?source=jobs_registration&amp;session_redirect=https%3A%2F%2Fwww.linkedin.com%2Fjobs%2Fsearch%2F%3Fkeywords%3Dcyber%2520security%26location%3DAustralia&amp;trk=public_jobs_nav-header-join"
  },
  {
    "id": "linkedin-au-cyber-jobs-sign-in",
    "title": "Sign in",
    "organization": "linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from linkedin.com: Sign in.",
    "url": "https://www.linkedin.com/login?emailAddress=&amp;fromSignIn=&amp;fromSignIn=true&amp;session_redirect=https%3A%2F%2Fwww.linkedin.com%2Fjobs%2Fsearch%2F%3Fkeywords%3Dcyber%2520security%26location%3DAustralia&amp;trk=public_jobs_nav-header-signin"
  },
  {
    "id": "linkedin-au-cyber-jobs-sign-in-to-create-job-alert",
    "title": "Sign in to create job alert",
    "organization": "linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from linkedin.com: Sign in to create job alert.",
    "url": "https://www.linkedin.com/login?emailAddress=&amp;fromSignIn=&amp;session_redirect=https%3A%2F%2Fwww.linkedin.com%2Fjobs%2Fsearch%2F%3Fkeywords%3Dcyber%2520security%26location%3DAustralia&amp;trk=public_jobs_job-alert-guest-redirect-cta"
  },
  {
    "id": "linkedin-au-cyber-jobs-technical-security-officer-enterprise-technology-and-security",
    "title": "Technical Security Officer, Enterprise Technology and Security",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Technical Security Officer, Enterprise Technology and Security.",
    "url": "https://au.linkedin.com/jobs/view/technical-security-officer-enterprise-technology-and-security-at-department-of-the-prime-minister-and-cabinet-4413640894?position=1&amp;pageNum=0&amp;refId=GoYTyKPYbZVZ%2BXndMZGGyQ%3D%3D&amp;trackingId=RrXMnw1dOsZ3VgnGvXNhXw%3D%3D"
  },
  {
    "id": "linkedin-au-cyber-jobs-junior-grc-analyst",
    "title": "Junior GRC Analyst",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Junior GRC Analyst.",
    "url": "https://au.linkedin.com/jobs/view/junior-grc-analyst-at-leap-legal-software-4408974726?position=2&amp;pageNum=0&amp;refId=GoYTyKPYbZVZ%2BXndMZGGyQ%3D%3D&amp;trackingId=mVPduFPvDJohI2N%2FuvbJeQ%3D%3D"
  },
  {
    "id": "linkedin-au-cyber-jobs-cybersecurity-specialist-remote",
    "title": "Cybersecurity Specialist | Remote",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Cybersecurity Specialist | Remote.",
    "url": "https://au.linkedin.com/jobs/view/cybersecurity-specialist-remote-at-codegeniusrecruit-4417571087?position=3&amp;pageNum=0&amp;refId=GoYTyKPYbZVZ%2BXndMZGGyQ%3D%3D&amp;trackingId=Y2ITMcx52ipbB5PbkdFi3g%3D%3D"
  },
  {
    "id": "linkedin-au-cyber-jobs-cyber-security-analyst",
    "title": "Cyber Security Analyst",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Cyber Security Analyst.",
    "url": "https://au.linkedin.com/jobs/view/cyber-security-analyst-at-centorrino-technologies-4373517728?position=5&amp;pageNum=0&amp;refId=GoYTyKPYbZVZ%2BXndMZGGyQ%3D%3D&amp;trackingId=KIN8d0DXgB7WTEc%2B%2FIzW7w%3D%3D"
  },
  {
    "id": "linkedin-au-cyber-jobs-enterprise-security-manager",
    "title": "Enterprise Security Manager",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Enterprise Security Manager.",
    "url": "https://au.linkedin.com/jobs/view/enterprise-security-manager-at-canva-4414428005?position=6&amp;pageNum=0&amp;refId=GoYTyKPYbZVZ%2BXndMZGGyQ%3D%3D&amp;trackingId=YFAwUEEY1q%2FcrrorlgLTrQ%3D%3D"
  },
  {
    "id": "linkedin-au-cyber-jobs-security-analyst",
    "title": "Security Analyst",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Security Analyst.",
    "url": "https://au.linkedin.com/jobs/view/security-analyst-at-sener-4407569230?position=7&amp;pageNum=0&amp;refId=GoYTyKPYbZVZ%2BXndMZGGyQ%3D%3D&amp;trackingId=DCI2C7wuBP9jlxEvAVrYGQ%3D%3D"
  },
  {
    "id": "linkedin-au-cyber-jobs-cybersecurity-expert",
    "title": "Cybersecurity Expert",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Cybersecurity Expert.",
    "url": "https://au.linkedin.com/jobs/view/cybersecurity-expert-at-great-value-hiring-4417840203?position=8&amp;pageNum=0&amp;refId=GoYTyKPYbZVZ%2BXndMZGGyQ%3D%3D&amp;trackingId=zePqkbVCATk8qFuWRHGWhw%3D%3D"
  },
  {
    "id": "linkedin-au-cyber-jobs-cyber-security-consultant",
    "title": "Cyber Security Consultant",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Cyber Security Consultant.",
    "url": "https://au.linkedin.com/jobs/view/cyber-security-consultant-at-securityhq-4411876622?position=9&amp;pageNum=0&amp;refId=GoYTyKPYbZVZ%2BXndMZGGyQ%3D%3D&amp;trackingId=Y0eYktv2RBqFECZk40s0fA%3D%3D"
  },
  {
    "id": "google-au-ai-jobs-click-here",
    "title": "click here",
    "organization": "google.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "software-engineering",
    "source": "company",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-05-24",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-05-24",
    "sourceNote": "Weekly auto-collected from https://www.google.com/search?q=site%3Acareers.google.com+Australia+AI+jobs on 2026-05-24. Public search pages can change, so review before applying.",
    "tags": [
      "Google Search",
      "auto-collected",
      "AI"
    ],
    "summary": "Weekly auto-collected industry role from google.com: click here.",
    "url": "https://www.google.com/search?q=site:careers.google.com+Australia+AI+jobs&amp;sca_esv=c2ae7bdc94c3d893&amp;emsg=SG_REL&amp;sei=Z4MTaqjQN5-lptQPp7W6IA"
  }
];
