window.JOB_DATA = [
  {
    "id": "anu-research-jobs-director-research-school-of-social-sciences",
    "title": "Director, Research School of Social Sciences",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Director, Research School of Social Sciences.",
    "url": "https://jobs.anu.edu.au/jobs/director-research-school-of-social-sciences-canberra-act-act-australia"
  },
  {
    "id": "anu-research-jobs-research-officer",
    "title": "Research Officer",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Research Officer.",
    "url": "https://jobs.anu.edu.au/jobs/research-officer-canberra-act-act-australia-ef7dd11d-4353-4651-8dd1-4c4ac53d4996"
  },
  {
    "id": "anu-research-jobs-information-security-officer",
    "title": "Information Security Officer",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Information Security Officer.",
    "url": "https://jobs.anu.edu.au/jobs/information-security-officer-canberra-act-act-australia"
  },
  {
    "id": "anu-research-jobs-lecturer-or-senior-lecturer-up-to-four-positions-available",
    "title": "Lecturer or Senior Lecturer (up to four positions available)",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Lecturer or Senior Lecturer (up to four positions available).",
    "url": "https://jobs.anu.edu.au/jobs/lecturer-or-senior-lecturer-up-to-four-positions-available-canberra-act-act-australia"
  },
  {
    "id": "anu-research-jobs-change-manager-environmental-sustainability",
    "title": "Change Manager, Environmental Sustainability",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Change Manager, Environmental Sustainability.",
    "url": "https://jobs.anu.edu.au/jobs/change-manager-environmental-sustainability-canberra-act-act-australia"
  },
  {
    "id": "anu-research-jobs-research-services-administrator",
    "title": "Research Services Administrator",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Research Services Administrator.",
    "url": "https://jobs.anu.edu.au/jobs/research-services-administrator-canberra-act-act-australia-f8601bf3-dafd-4cdd-9a43-f833af9f1264"
  },
  {
    "id": "linkedin-au-cyber-jobs-skip-to-main-content",
    "title": "Skip to main content",
    "organization": "linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from linkedin.com: Skip to main content.",
    "url": "https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia#main-content"
  },
  {
    "id": "linkedin-au-cyber-jobs-join-now",
    "title": "Join now",
    "organization": "linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from linkedin.com: Join now.",
    "url": "https://www.linkedin.com/signup/cold-join?source=jobs_registration&amp;session_redirect=https%3A%2F%2Fwww.linkedin.com%2Fjobs%2Fsearch%2F%3Fkeywords%3Dcyber%2520security%26location%3DAustralia&amp;trk=public_jobs_nav-header-join"
  },
  {
    "id": "linkedin-au-cyber-jobs-sign-in",
    "title": "Sign in",
    "organization": "linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from linkedin.com: Sign in.",
    "url": "https://www.linkedin.com/login?emailAddress=&amp;fromSignIn=&amp;fromSignIn=true&amp;session_redirect=https%3A%2F%2Fwww.linkedin.com%2Fjobs%2Fsearch%2F%3Fkeywords%3Dcyber%2520security%26location%3DAustralia&amp;trk=public_jobs_nav-header-signin"
  },
  {
    "id": "linkedin-au-cyber-jobs-easy-apply",
    "title": "Easy Apply",
    "organization": "linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from linkedin.com: Easy Apply.",
    "url": "https://www.linkedin.com/jobs/search/?keywords=cyber+security&amp;location=Australia&amp;f_AL=true&amp;trk=public_jobs_filters_f_AL"
  },
  {
    "id": "linkedin-au-cyber-jobs-under-10-applicants",
    "title": "Under 10 applicants",
    "organization": "linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from linkedin.com: Under 10 applicants.",
    "url": "https://www.linkedin.com/jobs/search/?keywords=cyber+security&amp;location=Australia&amp;f_EA=true&amp;trk=public_jobs_filters_f_EA"
  },
  {
    "id": "linkedin-au-cyber-jobs-sign-in-to-create-job-alert",
    "title": "Sign in to create job alert",
    "organization": "linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from linkedin.com: Sign in to create job alert.",
    "url": "https://www.linkedin.com/login?emailAddress=&amp;fromSignIn=&amp;session_redirect=https%3A%2F%2Fwww.linkedin.com%2Fjobs%2Fsearch%2F%3Fkeywords%3Dcyber%2520security%26location%3DAustralia&amp;trk=public_jobs_job-alert-guest-redirect-cta"
  },
  {
    "id": "linkedin-au-cyber-jobs-cyber-security-engineer",
    "title": "Cyber Security Engineer",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Cyber Security Engineer.",
    "url": "https://au.linkedin.com/jobs/view/cyber-security-engineer-at-centorrino-technologies-4474550073?position=1&amp;pageNum=0&amp;refId=M7W5cxCqhRaEEGZ00J1JTw%3D%3D&amp;trackingId=dYNag0ZsC0JNsuN6S4k3ZQ%3D%3D"
  },
  {
    "id": "linkedin-au-cyber-jobs-cyber-security-operations-officer",
    "title": "Cyber Security Operations Officer",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Cyber Security Operations Officer.",
    "url": "https://au.linkedin.com/jobs/view/cyber-security-operations-officer-at-hobsons-bay-city-council-4470249463?position=2&amp;pageNum=0&amp;refId=M7W5cxCqhRaEEGZ00J1JTw%3D%3D&amp;trackingId=0xtUBmRjWdK9jvJCaELZiw%3D%3D"
  },
  {
    "id": "linkedin-au-cyber-jobs-offensive-security-consultant",
    "title": "Offensive Security Consultant",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Offensive Security Consultant.",
    "url": "https://au.linkedin.com/jobs/view/offensive-security-consultant-at-triskele-labs-4467433447?position=3&amp;pageNum=0&amp;refId=M7W5cxCqhRaEEGZ00J1JTw%3D%3D&amp;trackingId=pLA5JwWMkJskIIHx1W29zQ%3D%3D"
  },
  {
    "id": "linkedin-au-cyber-jobs-cyber-security-engineer-contract",
    "title": "Cyber Security Engineer (Contract)",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Cyber Security Engineer (Contract).",
    "url": "https://au.linkedin.com/jobs/view/cyber-security-engineer-contract-at-the-missing-link-4465361662?position=4&amp;pageNum=0&amp;refId=M7W5cxCqhRaEEGZ00J1JTw%3D%3D&amp;trackingId=vOJTBuWelFshU43pT1FOGg%3D%3D"
  },
  {
    "id": "linkedin-au-cyber-jobs-director-of-cybersecurity",
    "title": "Director of Cybersecurity",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Director of Cybersecurity.",
    "url": "https://au.linkedin.com/jobs/view/director-of-cybersecurity-at-emesent-4426552777?position=5&amp;pageNum=0&amp;refId=M7W5cxCqhRaEEGZ00J1JTw%3D%3D&amp;trackingId=4FgUYjPsWdvk0jqFI1L2Aw%3D%3D"
  },
  {
    "id": "linkedin-au-cyber-jobs-cyber-security-analyst",
    "title": "Cyber Security Analyst",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Cyber Security Analyst.",
    "url": "https://au.linkedin.com/jobs/view/cyber-security-analyst-at-teamified-4462359235?position=6&amp;pageNum=0&amp;refId=M7W5cxCqhRaEEGZ00J1JTw%3D%3D&amp;trackingId=tyvnV1cv7AJH18nITqY6Hg%3D%3D"
  },
  {
    "id": "google-au-ai-jobs-click-here",
    "title": "click here",
    "organization": "google.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "software-engineering",
    "source": "company",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-10-05",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-10-05",
    "sourceNote": "Weekly auto-collected from https://www.google.com/search?q=site%3Acareers.google.com+Australia+AI+jobs on 2026-10-05. Public search pages can change, so review before applying.",
    "tags": [
      "Google Search",
      "auto-collected",
      "AI"
    ],
    "summary": "Weekly auto-collected industry role from google.com: click here.",
    "url": "https://www.google.com/search?q=site:careers.google.com+Australia+AI+jobs&amp;sca_esv=ec734b9ba2f66c6f&amp;sxsrf=APpeQnvYLNlvrhGF2UWlEPoH9Ky5ZIdGZw:1791160563932&amp;emsg=SG_REL&amp;sei=8_DCaoS_OKWmqtsPnaqZgQI"
  }
];
