window.JOB_DATA = [
  {
    "id": "anu-research-jobs-computational-rna-biology-research-officer",
    "title": "Computational RNA Biology Research Officer",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Computational RNA Biology Research Officer.",
    "url": "https://jobs.anu.edu.au/jobs/computational-rna-biology-research-officer-canberra-act-act-australia"
  },
  {
    "id": "anu-research-jobs-senior-research-project-manager",
    "title": "Senior Research Project Manager",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Senior Research Project Manager.",
    "url": "https://jobs.anu.edu.au/jobs/senior-research-project-manager-canberra-act-act-australia"
  },
  {
    "id": "anu-research-jobs-research-fellow",
    "title": "Research Fellow",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Research Fellow.",
    "url": "https://jobs.anu.edu.au/jobs/research-fellow-canberra-act-act-australia-f98a15bd-d6ac-411e-a856-f3f3cabe07a4"
  },
  {
    "id": "anu-research-jobs-research-services-administrator",
    "title": "Research Services Administrator",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Research Services Administrator.",
    "url": "https://jobs.anu.edu.au/jobs/research-services-administrator-canberra-act-act-australia"
  },
  {
    "id": "anu-research-jobs-research-management-officer",
    "title": "Research Management Officer",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Research Management Officer.",
    "url": "https://jobs.anu.edu.au/jobs/research-management-officer-canberra-act-act-australia-50b13a90-a482-4f43-83fe-ecd6d8f2b7b9"
  },
  {
    "id": "anu-research-jobs-candidate-details",
    "title": "Candidate Details",
    "organization": "Australian National University",
    "location": "Australia",
    "region": "australia",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "company",
    "status": "active",
    "workMode": "on-site",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://jobs.anu.edu.au/cw/en/listing/ on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "ANU",
      "auto-discovered",
      "research"
    ],
    "summary": "Weekly auto-collected research role from Australian National University: Candidate Details.",
    "url": "https://jobs.anu.edu.au/v1/candidate_details"
  },
  {
    "id": "linkedin-au-cyber-jobs-skip-to-main-content",
    "title": "Skip to main content",
    "organization": "linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from linkedin.com: Skip to main content.",
    "url": "https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia#main-content"
  },
  {
    "id": "linkedin-au-cyber-jobs-join-now",
    "title": "Join now",
    "organization": "linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from linkedin.com: Join now.",
    "url": "https://www.linkedin.com/signup/cold-join?source=jobs_registration&amp;session_redirect=https%3A%2F%2Fwww.linkedin.com%2Fjobs%2Fsearch%2F%3Fkeywords%3Dcyber%2520security%26location%3DAustralia&amp;trk=public_jobs_nav-header-join"
  },
  {
    "id": "linkedin-au-cyber-jobs-sign-in",
    "title": "Sign in",
    "organization": "linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from linkedin.com: Sign in.",
    "url": "https://www.linkedin.com/login?emailAddress=&amp;fromSignIn=&amp;fromSignIn=true&amp;session_redirect=https%3A%2F%2Fwww.linkedin.com%2Fjobs%2Fsearch%2F%3Fkeywords%3Dcyber%2520security%26location%3DAustralia&amp;trk=public_jobs_nav-header-signin"
  },
  {
    "id": "linkedin-au-cyber-jobs-sign-in-to-create-job-alert",
    "title": "Sign in to create job alert",
    "organization": "linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from linkedin.com: Sign in to create job alert.",
    "url": "https://www.linkedin.com/login?emailAddress=&amp;fromSignIn=&amp;session_redirect=https%3A%2F%2Fwww.linkedin.com%2Fjobs%2Fsearch%2F%3Fkeywords%3Dcyber%2520security%26location%3DAustralia&amp;trk=public_jobs_job-alert-guest-redirect-cta"
  },
  {
    "id": "linkedin-au-cyber-jobs-level-1-security-analyst",
    "title": "Level 1 Security Analyst",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Level 1 Security Analyst.",
    "url": "https://au.linkedin.com/jobs/view/level-1-security-analyst-at-triskele-labs-4387672477?refId=R4dPi356wVgU1e9pjgYb8Q%3D%3D&amp;trackingId=q94aH%2FzbkiiWGG6LhJvaGA%3D%3D&amp;position=1&amp;pageNum=0"
  },
  {
    "id": "linkedin-au-cyber-jobs-cyber-security-advisor",
    "title": "Cyber Security Advisor",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Cyber Security Advisor.",
    "url": "https://au.linkedin.com/jobs/view/cyber-security-advisor-at-centorrino-technologies-4361329209?refId=R4dPi356wVgU1e9pjgYb8Q%3D%3D&amp;trackingId=iUuUvukXV4jmZ%2BwAaRxZ1Q%3D%3D&amp;position=2&amp;pageNum=0"
  },
  {
    "id": "linkedin-au-cyber-jobs-cyber-security-advisor",
    "title": "Cyber Security Advisor",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Cyber Security Advisor.",
    "url": "https://au.linkedin.com/jobs/view/cyber-security-advisor-at-centorrino-technologies-4339243324?refId=R4dPi356wVgU1e9pjgYb8Q%3D%3D&amp;trackingId=ZPuy8BXPm%2B%2Fs%2B5xSOpMrQg%3D%3D&amp;position=3&amp;pageNum=0"
  },
  {
    "id": "linkedin-au-cyber-jobs-cybersecurity-trainee-fully-remote-upto-60-hr-hourly",
    "title": "Cybersecurity Trainee - Fully Remote | Upto $60/hr Hourly",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Cybersecurity Trainee - Fully Remote | Upto $60/hr Hourly.",
    "url": "https://au.linkedin.com/jobs/view/cybersecurity-trainee-fully-remote-upto-%2460-hr-hourly-at-mercor-4399204564?refId=R4dPi356wVgU1e9pjgYb8Q%3D%3D&amp;trackingId=dy6UVadHQLg%2BZl7xpv4%2FUA%3D%3D&amp;position=4&amp;pageNum=0"
  },
  {
    "id": "linkedin-au-cyber-jobs-cyber-security-advisor",
    "title": "Cyber Security Advisor",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Cyber Security Advisor.",
    "url": "https://au.linkedin.com/jobs/view/cyber-security-advisor-at-centorrino-technologies-4358450104?refId=R4dPi356wVgU1e9pjgYb8Q%3D%3D&amp;trackingId=LCEtHRGLuy7A62GoHovt5w%3D%3D&amp;position=5&amp;pageNum=0"
  },
  {
    "id": "linkedin-au-cyber-jobs-cyber-security-analyst",
    "title": "Cyber Security Analyst",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Cyber Security Analyst.",
    "url": "https://au.linkedin.com/jobs/view/cyber-security-analyst-at-centorrino-technologies-4373517728?refId=R4dPi356wVgU1e9pjgYb8Q%3D%3D&amp;trackingId=9lIe%2BsotczxHMGOXwAxl%2FA%3D%3D&amp;position=6&amp;pageNum=0"
  },
  {
    "id": "linkedin-au-cyber-jobs-cyber-security-advisor",
    "title": "Cyber Security Advisor",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Cyber Security Advisor.",
    "url": "https://au.linkedin.com/jobs/view/cyber-security-advisor-at-centorrino-technologies-4361624472?refId=R4dPi356wVgU1e9pjgYb8Q%3D%3D&amp;trackingId=UM0ZOXf3D%2BDjhUy7J356Uw%3D%3D&amp;position=7&amp;pageNum=0"
  },
  {
    "id": "linkedin-au-cyber-jobs-cyber-security-advisor",
    "title": "Cyber Security Advisor",
    "organization": "au.linkedin.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "cybersecurity",
    "source": "linkedin",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.linkedin.com/jobs/search/?keywords=cyber%20security&location=Australia on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "LinkedIn",
      "auto-collected",
      "cyber"
    ],
    "summary": "Weekly auto-collected industry role from au.linkedin.com: Cyber Security Advisor.",
    "url": "https://au.linkedin.com/jobs/view/cyber-security-advisor-at-centorrino-technologies-4361309610?refId=R4dPi356wVgU1e9pjgYb8Q%3D%3D&amp;trackingId=yL2oRWRaNhu0tRwXN6jT9Q%3D%3D&amp;position=8&amp;pageNum=0"
  },
  {
    "id": "seek-ai-auckland-sign-in",
    "title": "Sign in",
    "organization": "seek.co.nz",
    "location": "New Zealand",
    "region": "new-zealand",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "seek",
    "status": "active",
    "workMode": "remote",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.seek.co.nz/ai-research-jobs/in-All-Auckland on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "SEEK",
      "auto-discovered",
      "AI"
    ],
    "summary": "Weekly auto-collected research role from seek.co.nz: Sign in.",
    "url": "https://www.seek.co.nz/oauth/login?returnUrl=%2Fai-research-jobs%2Fin-All-Auckland"
  },
  {
    "id": "seek-ai-auckland-thailand",
    "title": "Thailand",
    "organization": "th.jobsdb.com",
    "location": "New Zealand",
    "region": "new-zealand",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "seek",
    "status": "active",
    "workMode": "remote",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.seek.co.nz/ai-research-jobs/in-All-Auckland on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "SEEK",
      "auto-discovered",
      "AI"
    ],
    "summary": "Weekly auto-collected research role from th.jobsdb.com: Thailand.",
    "url": "https://th.jobsdb.com/"
  },
  {
    "id": "seek-ai-auckland-accounting",
    "title": "Accounting",
    "organization": "seek.co.nz",
    "location": "New Zealand",
    "region": "new-zealand",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "seek",
    "status": "active",
    "workMode": "remote",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.seek.co.nz/ai-research-jobs/in-All-Auckland on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "SEEK",
      "auto-discovered",
      "AI"
    ],
    "summary": "Weekly auto-collected research role from seek.co.nz: Accounting.",
    "url": "https://www.seek.co.nz/ai-research-jobs-in-accounting/in-All-Auckland"
  },
  {
    "id": "seek-ai-auckland-administration-and-office-support",
    "title": "Administration & Office Support",
    "organization": "seek.co.nz",
    "location": "New Zealand",
    "region": "new-zealand",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "seek",
    "status": "active",
    "workMode": "remote",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.seek.co.nz/ai-research-jobs/in-All-Auckland on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "SEEK",
      "auto-discovered",
      "AI"
    ],
    "summary": "Weekly auto-collected research role from seek.co.nz: Administration & Office Support.",
    "url": "https://www.seek.co.nz/ai-research-jobs-in-administration-office-support/in-All-Auckland"
  },
  {
    "id": "seek-ai-auckland-advertising-arts-and-media",
    "title": "Advertising, Arts & Media",
    "organization": "seek.co.nz",
    "location": "New Zealand",
    "region": "new-zealand",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "seek",
    "status": "active",
    "workMode": "remote",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.seek.co.nz/ai-research-jobs/in-All-Auckland on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "SEEK",
      "auto-discovered",
      "AI"
    ],
    "summary": "Weekly auto-collected research role from seek.co.nz: Advertising, Arts & Media.",
    "url": "https://www.seek.co.nz/ai-research-jobs-in-advertising-arts-media/in-All-Auckland"
  },
  {
    "id": "seek-ai-auckland-banking-and-financial-services",
    "title": "Banking & Financial Services",
    "organization": "seek.co.nz",
    "location": "New Zealand",
    "region": "new-zealand",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "seek",
    "status": "active",
    "workMode": "remote",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.seek.co.nz/ai-research-jobs/in-All-Auckland on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "SEEK",
      "auto-discovered",
      "AI"
    ],
    "summary": "Weekly auto-collected research role from seek.co.nz: Banking & Financial Services.",
    "url": "https://www.seek.co.nz/ai-research-jobs-in-banking-financial-services/in-All-Auckland"
  },
  {
    "id": "seek-ai-auckland-call-centre-and-customer-service",
    "title": "Call Centre & Customer Service",
    "organization": "seek.co.nz",
    "location": "New Zealand",
    "region": "new-zealand",
    "track": "research",
    "roleFamily": "ai-research",
    "source": "seek",
    "status": "active",
    "workMode": "remote",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.seek.co.nz/ai-research-jobs/in-All-Auckland on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "SEEK",
      "auto-discovered",
      "AI"
    ],
    "summary": "Weekly auto-collected research role from seek.co.nz: Call Centre & Customer Service.",
    "url": "https://www.seek.co.nz/ai-research-jobs-in-call-centre-customer-service/in-All-Auckland"
  },
  {
    "id": "google-au-ai-jobs-click-here",
    "title": "click here",
    "organization": "google.com",
    "location": "Australia",
    "region": "australia",
    "track": "industry",
    "roleFamily": "software-engineering",
    "source": "company",
    "status": "active",
    "workMode": "hybrid",
    "postedDate": null,
    "postedLabel": "Collected 2026-04-12",
    "closingDate": null,
    "priorityScore": 72,
    "verifiedDate": "2026-04-12",
    "sourceNote": "Weekly auto-collected from https://www.google.com/search?q=site%3Acareers.google.com+Australia+AI+jobs on 2026-04-12. Public search pages can change, so review before applying.",
    "tags": [
      "Google Search",
      "auto-collected",
      "AI"
    ],
    "summary": "Weekly auto-collected industry role from google.com: click here.",
    "url": "https://www.google.com/search?q=site:careers.google.com+Australia+AI+jobs&amp;sca_esv=41e6c9bad912c352&amp;emsg=SG_REL&amp;sei=YR_cafXHCJrdptQPvuXX4A8"
  }
];
